spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
# 这是重点， 会过滤.html后缀的文件
spring.freemarker.suffix: .html
#spring boot 默认的页面模板存放目录  
spring.freemarker.template-loader-path: classpath:/templates/    
spring.freemarker.cache: false 
mybatis:
  mapper-locations: classpath:mapper/*.xml            #XML文件